baseURL = "https://www.vimiix.com/"
languageCode = "cn-zh"
title = "Hi, I'm Vimiix"
theme = "smol"
copyright = "Vimiix Yao; All rights reserved"
buildFuture = true
pagination.pagerSize = 20
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

# Parameters
[params]
authorName = "Vimiix Yao"
githubUser = "vimiix"
subtitle = "Get hands dirty."
dateFmt = "2006.01.02 15:04"
keywords = ["Technology", "Code", "Program", "Python", "Golang", "vimiix"]
description = "A blog maintained by Vimiix."

# Header
[menu]
[[menu.main]]
identifier = "posts"
name = "文章列表"
url = "/posts/"
weight = 1
# [[menu.main]]
# identifier = "categories"
# name = "分类"
# url = "/categories/"
# weight = 2
[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 3
[[menu.main]]
identifier = "friends"
name = "友链"
url = "/friends/"
weight = "4"
[[menu.main]]
identifier = "about"
name = "关于我"
url = "/about/"
weight = "5"
[[menu.main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
weight = "6"
[[menu.main]]
identifier = "ssx"
name = "开源项目"
url = "/projects/"
weight = "3"

# Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/vimiix"
weight = 1

[[menu.footer]]
name = "Douban"
url = "https://www.douban.com/people/vimiix/"
weight = 2

[[menu.footer]]
name = "Email"
url = "mailto:i@vimiix.com"
weight = 3
